[package]
name = "paber"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
nix = { version = "0.27", features = ["fs", "mman"] }
